services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drone_ros2
    tty: true
    stdin_open: true
    working_dir: /workspaces/drone_ws
    privileged: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0  
    volumes:
      - ./drone_ws:/workspaces/drone_ws
